version: "3.9"
services:

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - "./psql_data:/var/lib/postgresql/data"
      - "./init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh"
    env_file:
      - .env
    ports:
      - "5432:5432"
